name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: JPL-SBIR-Comput

    steps:
    - uses: actions/checkout@v3

    - name: Build and push tagged image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/jrbe228/actions-runner-compose:$(date +%s)
          ghcr.io/jrbe228/actions-runner-compose:latest
