name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: Windows

    steps:
    - uses: actions/checkout@v3

    - name: Build and push tagged image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/jrbe228/actions-runner-compose:${{ github.run_number }}
          ghcr.io/jrbe228/actions-runner-compose:latest
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
